# Generated by Django 6.0.4 on 2026-04-20 19:04

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("CREATE_INVOICE", "Created Invoice"),
                            ("CREATE_PURCHASE", "Created Purchase"),
                            ("ADD_MEDICINE", "Added Medicine"),
                            ("UPDATE_MEDICINE", "Updated Medicine"),
                            ("DELETE_MEDICINE", "Deleted Medicine"),
                            ("IMPORT_EXCEL", "Imported Excel"),
                            ("EXPORT_DATA", "Exported Data"),
                            ("BACKUP_CREATE", "Created Backup"),
                            ("BACKUP_RESTORE", "Restored Backup"),
                            ("SETTINGS_CHANGE", "Changed Settings"),
                            ("PASSWORD_CHANGE", "Changed Password"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.TextField(blank=True, default="")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
