# Generated by Django 6.0.4 on 2026-04-20 19:04

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospital", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "gstin",
                    models.CharField(
                        blank=True, default="", max_length=15, verbose_name="GSTIN"
                    ),
                ),
                (
                    "credit_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Udhaar amount",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True, default="Walk-in Customer", max_length=255
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed Amount"),
                            ("PERCENTAGE", "Percentage"),
                        ],
                        default="FIXED",
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cgst",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="CGST"
                    ),
                ),
                (
                    "sgst",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="SGST"
                    ),
                ),
                (
                    "igst",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="IGST"
                    ),
                ),
                (
                    "total_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("UPI", "UPI"),
                            ("CARD", "Card"),
                            ("CREDIT", "Credit (Udhaar)"),
                            ("MIXED", "Mixed Payment"),
                        ],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "change_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="COMPLETED",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="billing.customer",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=255)),
                (
                    "batch_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("gst_rate", models.IntegerField(default=12)),
                (
                    "cgst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "sgst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "igst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.invoice",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_items",
                        to="inventory.medicine",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
