# Generated by Django 5.2.13 on 2026-04-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_payroll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Normal"),
                    ("GENERAL_WARD", "General Ward"),
                    ("EMERGENCY", "Emergency"),
                    ("PRIVATE_WARD", "Private Ward"),
                    ("PRIVATE_ROOM", "Private Room"),
                    ("SEMI_LUXURY", "Semi Luxury Room"),
                    ("STAFF_ROOM", "Staff Room"),
                    ("NURSE_STATION", "Nurse Station"),
                ],
                default="NORMAL",
                max_length=20,
            ),
        ),
    ]
