# Generated by Django 5.2.13 on 2026-04-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0004_alter_room_room_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="is_occupied",
        ),
        migrations.AddField(
            model_name="room",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("OCCUPIED", "Occupied"),
                    ("CLEANING", "Cleaning"),
                    ("MAINTENANCE", "Maintenance"),
                    ("EMERGENCY", "Emergency"),
                ],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="last_cleaned",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="room",
            name="occupant_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "Patient"),
                    ("D", "Doctor"),
                    ("N", "Nurse"),
                    ("S", "Staff"),
                    ("EM", "Emergency"),
                ],
                max_length=5,
                null=True,
            ),
        ),
    ]
