# Generated by Django 5.2.13 on 2026-04-21 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0005_remove_room_is_occupied_room_current_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="assigned_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_housing",
                to="hospital.doctor",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="assigned_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_housing",
                to="hospital.staff",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Normal"),
                    ("GENERAL_WARD", "General Ward"),
                    ("EMERGENCY", "Emergency"),
                    ("PRIVATE_WARD", "Private Ward"),
                    ("PRIVATE_ROOM", "Private Room"),
                    ("SEMI_LUXURY", "Semi Luxury Room"),
                    ("LUXURY_SUITE", "Luxury Suite"),
                    ("STAFF_QUARTERS", "Staff Quarters"),
                    ("DOCTOR_HOUSING", "Doctor Housing"),
                    ("NURSE_QUARTERS", "Nurse Quarters"),
                    ("SECURITY_POST", "Security Post"),
                ],
                default="NORMAL",
                max_length=30,
            ),
        ),
    ]
