# Generated by Django 5.2.13 on 2026-04-22 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0006_room_assigned_doctor_room_assigned_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambulancedispatch",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ambulance_dispatches",
                to="hospital.patient",
            ),
        ),
        migrations.AddField(
            model_name="labtest",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_tests",
                to="hospital.patient",
            ),
        ),
        migrations.AlterField(
            model_name="ambulancedispatch",
            name="patient_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="patient_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
