# Generated by Django 6.0.4 on 2026-04-20 19:04

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "gstin",
                    models.CharField(
                        blank=True, default="", max_length=15, verbose_name="GSTIN"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "generic_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("batch_number", models.CharField(db_index=True, max_length=100)),
                (
                    "barcode",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TABLET", "Tablet"),
                            ("CAPSULE", "Capsule"),
                            ("SYRUP", "Syrup"),
                            ("INJECTION", "Injection"),
                            ("CREAM", "Cream/Ointment"),
                            ("DROPS", "Drops"),
                            ("POWDER", "Powder"),
                            ("SURGICAL", "Surgical"),
                            ("AYURVEDIC", "Ayurvedic"),
                            ("OTHER", "Other"),
                        ],
                        default="TABLET",
                        max_length=20,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "mrp",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="MRP"
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "gst_rate",
                    models.IntegerField(
                        choices=[
                            (0, "Exempt (0%)"),
                            (5, "GST 5%"),
                            (12, "GST 12%"),
                            (18, "GST 18%"),
                            (28, "GST 28%"),
                        ],
                        default=12,
                        verbose_name="GST Rate (%)",
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="HSN Code"
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "min_stock_level",
                    models.IntegerField(
                        default=10, help_text="Alert when stock falls below this"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="Pcs",
                        help_text="e.g., Pcs, Strip, Bottle",
                        max_length=50,
                    ),
                ),
                ("expiry_date", models.DateField()),
                ("manufacturing_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "rack_location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Storage location",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medicines",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["name", "batch_number"],
                        name="inventory_m_name_2fc32c_idx",
                    ),
                    models.Index(
                        fields=["expiry_date"], name="inventory_m_expiry__3d60fd_idx"
                    ),
                    models.Index(
                        fields=["quantity"], name="inventory_m_quantit_3cd49e_idx"
                    ),
                ],
            },
        ),
    ]
